name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "1 0 * * FRI" # every FRI at 00:01
  workflow_dispatch: {} # manual release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: Publish site to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.6.0
        with:
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployment from GitHub Actions ${{ steps.vars.outputs.sha_short }} (${{ steps.vars.outputs.branch }})"
          build_directory: dist
